import { ContatosPage } from "./ContatosPage"
import { DashboardPage } from "./DashboardPage"
import { LoginPage } from "./LoginPage"
import { NotFoundPage } from "./NotFoundPage"
import { PerfilPage } from "./PerfilPage"
import { RegisterPage } from "./RegisterPage"
