version: '3.9'
services:

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/authdb
    depends_on:
      - auth-db

  contact-service:
    build: ./contact-service
    ports:
      - "8082:8082"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://contact-db:5432/contactdb
    depends_on:
      - contact-db
      - auth-service

  auth-db:
    image: postgres:16
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  contact-db:
    image: postgres:16
    environment:
      POSTGRES_DB: contactdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres